### ISSUE TITLE
XAuth → OAuth

### ISSUE THREAD

**Issue by blueset** [simpleapples/fanfou-10th-anniversary#2]
是否考虑将 目前的 XAuth 替换为 OAuth 认证模式？

XAuth 明文传输/存储用户认证信息可能会造成安全问题以及用户的安全性担忧。

**Comment by simpleapples** [comment]
考虑过，时间比较紧，所以就先用XAuth了，看看有没有时间改成OAuth

**Comment by blueset** [comment]
Fixed.
